import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'

interface Props {
    children: React.ReactNode,
    noFooter?: boolean,
    noHeader?: boolean
}

const Layout: React.FC<Props> = ({children, noFooter, noHeader}) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta
                name="viewport"
                content="minimum-scale=1, initial-scale=1, width=device-width"
                />
            </Head>
            { !noHeader &&
                <header> <Header/> </header>
            }
            <main> {children} </main>
            { !noFooter &&
                <footer> <Footer/> </footer>
            }
        </div>
    )
}

export default Layout